import { Poppins } from "next/font/google";
import "./globals.css";
import ClickSpark from '../components/ClickSpark';

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata = {
  title: "Achieve",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased`}>
          <ClickSpark
          sparkColor='#102873'
          sparkSize={12}
          sparkRadius={15}
          sparkCount={8}
          duration={500}
        >
              {children}
      </ClickSpark>
      </body>
    </html>
  );
}
